<a href="https://colab.research.google.com/github/wanhee-lee-stanford/AP228/blob/Ex-0/AP_228_Ex_1_Python_for_basic_quantum_calculations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Python Primer for Quantum Calculations

In this notebook we introduce python packages that help implement the matrix representation of operators. 

If this is your first time using Python, [click this link](https://www.w3schools.com/python/default.asp) and go through the following sections: "Python Tutorial", "Introduction to NumPy", and "Introduction to Matplotlib". You may use any other reference as well.

In [ ]:
import matplotlib.pyplot as plt
import numpy as np
from scipy import linalg


# Definitions of operators

Here we define functions for the creation/annhilation operators $\hat{a}^\dagger,\hat{a}$, as well as the Pauli operators $\hat{\sigma}_j$ for $j=x,y,z$. 

Think about why the creation/annhilation operators have an input argument, whereas the pauli matrices do not.

In [ ]:
## Creation operator 
def ad_op(N):
    ad = np.zeros((N,N))
    for k in range(N-1):
        ad[k+1,k]=np.sqrt(k+1)
    return np.matrix(ad)

# Annhilation operator
def a_op(N):
    ad = ad_op(N)
    return ad.transpose()


## Pauli Matrices

def sigmax():
    sx = np.zeros((2,2),dtype=complex) # it is important to define as complex matrices!
    sx[0,1]=1
    sx[1,0]=1
    return np.matrix(sx)

def sigmaz():
    sz = np.zeros((2,2),dtype=complex)
    sz[0,0]=1
    sz[1,1]=-1
    return np.matrix(sz)

def sigmay():
    sy = np.zeros((2,2),dtype=complex)
    sy[0,1]=-1j
    sy[1,0]=1j
    return np.matrix(sy)

# Harmonic oscillator Hamiltonian and evolution

We choose a size $N$ for our Fock space. We can represent our Hamiltonian as shown below, and even use matrix exponentiation to find the propagator $U$.

In [ ]:
# dimensionality of the fock space
N = 5 

# number operator
n_op = ad_op(N)*a_op(N)

# frequency of oscillation (rad/sec)
omega = 1

# time elapsed pi (sec)
t= np.pi

# define hamiltonian
H = omega*(n_op+np.eye(5)*0.5)

# define propagator
U = np.matrix(linalg.expm(-1j*H*t))

# initialize in ground state
psi = np.matrix(np.zeros((N,1)));
psi[0]=1

# see what propagator does to ground state |0>
print()
print(psi)
print()
print(U*psi)
print()
print("---")

# initialize in first excited state |1>
psi = np.matrix(np.zeros((N,1)));
psi[1]=1

# see what various operators do to state |1>
print()
print(psi)
print()
print(ad_op(N))
print()
print(ad_op(N)*psi)
print()


[[1.]
 [0.]
 [0.]
 [0.]
 [0.]]

[[6.123234e-17-1.j]
 [0.000000e+00+0.j]
 [0.000000e+00+0.j]
 [0.000000e+00+0.j]
 [0.000000e+00+0.j]]

---

[[0.]
 [1.]
 [0.]
 [0.]
 [0.]]

[[0.         0.         0.         0.         0.        ]
 [1.         0.         0.         0.         0.        ]
 [0.         1.41421356 0.         0.         0.        ]
 [0.         0.         1.73205081 0.         0.        ]
 [0.         0.         0.         2.         0.        ]]

[[0.        ]
 [0.        ]
 [1.41421356]
 [0.        ]
 [0.        ]]



# Coordinate Rotations

We can use python's linear algebra packages to exponentiate matrices. 

A rotation by angle $\theta$ about the $x$-axis is given by $$\exp(i\hat{\sigma}_x\theta/2).$$ 

Below we code the situation when $\theta=\pi/2$, $$\exp(i\hat{\sigma}_x\pi/4).$$

In [ ]:
sigmax()*sigmay()

linalg.expm(1j*sigmax()*np.pi/4)


array([[0.70710678+0.j        , 0.        +0.70710678j],
       [0.        +0.70710678j, 0.70710678+0.j        ]])

### Exercises

1. Familiarize yourself with python and the functions in this notebook.

2. Write python function called `D_op(alpha,N)` that generates the displacement operator.

3. Write a python function called `Parity(N)` which generates the Parity operator.


#### Bonus

4. The Hadamard matrix is given by $$H=\frac{1}{\sqrt{2}}\begin{pmatrix}
1 & 1\\
1 & -1 
\end{pmatrix}. $$ Try to express this as a sequence of rotations about  $x$, $y$, $z$.